# Site settings 配置站点
title: '宋一峰的博客'
description: 'Just for fun !'
keywords: '宋一峰, javascript, Linux, 网络'
url: 'https://ots988.github.io/' # your host

# nav 中文字符空格：&emsp;
nav: # 最佳体验 六个标签 且最好每个标签不超过4中文字
  首页: '/'
  标签: '/tags.html'
  时间线: '/timeline.html'
  关于博主: '/about.html'
  #个人简历: '/resume/index.html'
  前端作品: '/friendLink.html'

# 博主
author: true
name: '宋一峰'
NickName: 'Arthur'
webtitle: 'Arthur'
bio: '软件工程师'
about: true
aboutyou: '&emsp;&emsp;来不及介绍，下次补之。
        '
portraits: '/assets/profile.jpeg'

# SNS
SNS: true
SNS-icon: #['Facebook', 'weibo', 'qq', 'github', 'Dribbble', 'Twitter', 'instagram', 'weixin', 'Codepen']
  mail: 'mailto:ots988@163.com'
  github: 'https://github.com/ots988'
  Codepen: ''
  weixin: '/assets/scan/wechat.JPG'
  # qq: '/assets/scan/qq.JPG'
  qq: 'http://wpa.qq.com/msgrd?v=3&uin=1021510797&site=qq&menu=yes'
  weibo: ''
  instagram: ''
  Twitter: ''
  # Dribbble: ''s
  # Facebook: ''
  # Google: ''
  # zhihu: ''
  # juejin: ''
  # twitch: ''

# 分页
paginate: 5
paginatepath: ['page:num']

# since
footer:
  since: 2018

# Markdown
markdown: kramdown
kramdown:
  input: GFM
# 代码高亮 使用rouge
highlighter: rouge
# 代码高亮主题使用pygments主题: autumn\ default\ emacs\ friendly\ manni\ murphy\ pastie\ perldoc\ tango 任选一个你喜欢的主题名称填在下面的单引号中
pygmentsTheme: 'tango'

# 友情链接
friends:
  前端简历: 'https://ots988.github.io/jianli/'
  #前端酷炫效果: 'https://my.csdn.net/caojidasabi?locationNum=0&fps=1'

# 评论 最佳体验 在disqus、livere和Gitment之间三选一
# disqus 评论
disqus: false
disqus_url: 'https://talkcock.disqus.com/embed.js'
# 来必力评论
livere: true
livere_uid: 'MTAyMC8zNDI2OS8xMDgwNg=='
# Gitment评论 OAuth Application
Gitment: false
Gitment_owner: 'xukimseven'  # github用户名
Gitment_repo: 'xukimseven.github.io'  # github博客存放的仓库名
client_id: '72361128c7951f78f718'  # 注册 OAuth Application 后获得的 client_id
client_secret: '96f9d49e9be0dd79df862cd84cf24a421b91835e'  # 注册 OAuth Application 后获得的 client_secret

# Share : weibo, qq, wechat, tencent, douban, qzone, linkedin, diandian, facebook, twitter, google
social-share: true
social-share-items: ['qq', 'wechat', 'weibo', 'twitter', 'facebook']

# 百度统计 在baidu-url里填写自己相关的url代码
baidu: true
baidu-url: 'efa555a0adb0eca621754fde118fb358'
# 谷歌分析 在google-ID里填写自己在谷歌分析获得的追踪ID
google: false
google-ID: 'UA-119823655-1'

# 博客头信息备选颜色（该部分在站点中不充当站点变量，将其写在post的头信息中用来充当页面变量）
color: rgb(154,133,255) rgb(255,90,90) rgb(255,210,32) rgb(98,170,255)

exclude:
  - README.md
  - /bak